<?php

use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * @file
 * Functions to support theming.
 */

/**
 * Implements hook_preprocess_image_widget().
 */
function sea_trips_preprocess_image_widget(array &$variables): void
{
  $data = &$variables['data'];

  // This prevents image widget templates from rendering preview container HTML
  // to users that do not have permission to access these previews.
  // @todo revisit in https://drupal.org/node/953034
  // @todo revisit in https://drupal.org/node/3114318
  if (isset($data['preview']['#access']) && $data['preview']['#access'] === FALSE) {
    unset($data['preview']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for theme settings.
 */
function sea_trips_form_system_theme_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state)
{
  // Add a custom color input field to the theme settings form.
  $form['header_background'] = [
    '#type' => 'managed_file',
    '#title' => new TranslatableMarkup('Background for static pages'),
    '#description' => new TranslatableMarkup('Header background'),
    '#default_value' => \Drupal::config('sea_trips.settings')->get('header_background') ?? [],
    '#upload_location' => 'public://',
  ];
  $form['primary_color'] = [
    '#type' => 'color',
    '#title' => new TranslatableMarkup('Custom Color'),
    '#default_value' => theme_get_setting('primary_color'),
    '#description' => new TranslatableMarkup('Select a custom theme color.'),
  ];
  $form['phone_number'] = [
    '#type' => 'textfield',
    '#title' => new TranslatableMarkup('Phone number'),
    '#default_value' => theme_get_setting('phone_number'),
    '#description' => new TranslatableMarkup('Set phone number used on the page.')
  ];
  $form['street_name'] = [
    '#type' => 'textfield',
    '#title' => new TranslatableMarkup('Street Name'),
    '#default_value' => theme_get_setting('street_name'),
    '#description' => new TranslatableMarkup('Street name for contact information.'),
  ];

  $form['city_name'] = [
    '#type' => 'textfield',
    '#title' => new TranslatableMarkup('City Name'),
    '#default_value' => theme_get_setting('city_name'),
    '#description' => new TranslatableMarkup('City name for contact information.'),
  ];

  $form['zip_code'] = [
    '#type' => 'textfield',
    '#title' => new TranslatableMarkup('Zip Code'),
    '#default_value' => theme_get_setting('zip_code'),
    '#description' => new TranslatableMarkup('Zip code for contact information.'),
  ];
}


/**
 * Implements hook_preprocess_region().
 */
function sea_trips_preprocess_region(array &$variables) {
  // Check if we are targeting the primary menu region.
  if ($variables['region'] === 'primary_menu') {

    if (\Drupal::service('path.matcher')->isFrontPage()) {
      $variables['is_pirate_slider'] = TRUE;
      return;
    }
    // Get the stored file ID from theme settings.
    $fid = theme_get_setting('header_background')[0];
    if (!empty($fid) && is_numeric($fid)) {
      // Load the file entity.
      $file = \Drupal\file\Entity\File::load($fid);
      if ($file) {
        // Use the new method to generate the absolute file URL.
        $uri = $file->getFileUri();
        $variables['header_background_url'] = \Drupal::service('file_url_generator')->generateAbsoluteString($uri);
      }
    }
  }
}

/**
 * Preprocess paragraph.
 * 
 * @param array $variables
 * 
 * @return void
 */
function sea_trips_preprocess_paragraph(array &$variables)
{
  $paragraph = $variables['paragraph'];
  if ($paragraph->bundle() === 'pricing_table') {

    if ($paragraph->hasField('field_pt_background_color')) {
      $color = $paragraph->get('field_pt_background_color')->getValue()[0]['value'] ?? '';

      $bg_color = 'bg-pricing-bg-';
      $btn_color = 'bg-pricing-btn-';
      switch ($color) {
        case 'orangish':
          $bg_color .= '1';
          $btn_color .= '1';
          break;

        case 'blueish':
          $bg_color .= '2';
          $btn_color .= '2';
          break;

        case 'pinky':
          $bg_color .= '3';
          $btn_color .= '3';
          break;

        default:
          $bg_color .= '1';
          $btn_color .= '1';
      }
      $variables['bg_color'] = $bg_color;
      $variables['btn_color'] = $btn_color;
    }
  }
  if ($paragraph->bundle() === 'akapit_informacyjny') {
    // Check if the paragraph has the field `field_st_background_color`
    if ($paragraph->hasField('field_st_background_color') && !$paragraph->get('field_st_background_color')->isEmpty()) {
      $backgroundColor = $paragraph->get('field_st_background_color')->value;
      $variables['is_primary_dark_color'] = isColorDarker($backgroundColor);
    }
  }
}



/**
 * Helper function to check if a color is dark.
 */
function isColorDarker(string $color = '#FFFFFF', string $referenceColor = '#888888'): bool
{
  $colorRgb = sscanf($color, "#%2x%2x%2x");
  $referenceRgb = sscanf($referenceColor, "#%2x%2x%2x");

  if ($colorRgb === NULL || $referenceRgb === NULL) {
    return FALSE;
  }

  // Calculate the luminance for each color.
  $colorLuminance = 0.299 * $colorRgb[0] + 0.587 * $colorRgb[1] + 0.114 * $colorRgb[2];
  $referenceLuminance = 0.299 * $referenceRgb[0] + 0.587 * $referenceRgb[1] + 0.114 * $referenceRgb[2];
  return $colorLuminance < $referenceLuminance;
}

/**
 * Implements hook_form_system_theme_settings_alter_submit().
 */
function sea_trips_form_system_theme_settings_alter_submit($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  // Get the uploaded file ID from the form state.
  $fid = $form_state->getValue('header_background');

  if (!empty($fid) && is_array($fid)) {
    $fid = reset($fid); // Extract file ID from array.
  }

  if (!empty($fid) && is_numeric($fid)) {
    $file = \Drupal\file\Entity\File::load($fid);
    if ($file) {
      // Mark the file as permanent.
      $file->setPermanent();
      $file->save();
    }
  }

  // Save the setting.
  \Drupal::configFactory()->getEditable('sea_trips.settings')->set('header_fbackground', $fid)->save();
}
